添加sqlite3数据库支持
flipped-aurora/gin-vue-admin pull request #1455
Opened 2023-06-15 14:00 UTC by Kafumio

完成状况：在代码层面为初始化和自动生成代码的功能模块提供了sqlite3数据库支持，修改了普通部署配置，但未修改docker部署下的配置。

问题：
1、sqlite3在数据库配置上跟目前支持的数据库大相径庭，我选择沿用统一的配置数据结构，是否有必要使用一个专用的配置数据结 
     构来支持sqlite3？
2、由于sqlite3为嵌入式数据库，没有数据库这一层级，所以查询数据库并切换的功能无法得到支持，只能使用初始化的gva数据 
     库，导致如果想用sqlite3数据库支持自动生成代码，元数据必须来自gva，很容易破坏初始化的表。

以上问题，希望审核人能为我提出一些意见，帮助我进行优化，谢谢。

2023-06-20 13:08 UTC, piexlmax commented
此功能需要windows单独安装gcc嘛？然后包名称有些不规范，可以合并到system下去书写。

2023-06-20 13:09 UTC, piexlmax commented
为了方便用户自己配置文件的划分，冗余一个sqlite3的单独配置块是被允许的。

2023-06-21 02:37 UTC, Kafumio commented
应该不需要gcc，包名称你能给个标准吗，谢谢

2023-06-21 12:05 UTC, pnck requested changes
由于这个原项目我也有一段时间没跟进过了，所以逻辑的部分没法review，只看了看非逻辑的东西。

还请owner们多看两眼检查下逻辑有没有问题。

2023-06-21 12:05 UTC, pnck commented on server/config.yaml
这个文件是不是引入了你自己的测试环境的修改？  能不能恢复一下，只增加必要的新选项就好了

2023-06-21 12:05 UTC, pnck commented on server/api/v1/test/enter.go
这个package是没用的对吧，应该清理掉

2023-06-21 12:05 UTC, pnck commented on server/initialize/router.go
> -	// 如果想要不使用nginx代理前端网页，可以修改 web/.env.production 下的
这文件里的注释怎么被清掉了

2023-06-21 12:05 UTC, pnck commented on server/router/enter.go
> +	Test    test.RouterGroup
~`test.RouterGroup`~

2023-06-21 12:05 UTC, pnck commented on server/service/system/sys_auto_code_sqlite.go
> +	sql := fmt.Sprintf("PRAGMA table_info(%s);", tableName)
sql注入？

2023-06-21 12:56 UTC, piexlmax commented on server/config.yaml
是的，我已经在上面给出了评论，配置文件被修改了。

2023-06-21 13:01 UTC, piexlmax commented
> 应该不需要gcc，包名称你能给个标准吗，谢谢

我这边再次看了一下，test包似乎是没有必要存在的，按照其他数据库实现配置，链接，初始化即可。需要修改的地方为配置文件需要重置为原来的模式，恢复注释。initialize下的文件恢复为原来格式，通过自动化代码产生的test包以及内容全部清理后可以再次提交。

2023-06-21 13:07 UTC, piexlmax commented on server/service/system/sys_auto_code_sqlite.go
> +	sql := fmt.Sprintf("PRAGMA table_info(%s);", tableName)
这块是必然注入的 不可以上正式环境。仅开发使用。

2023-06-22 08:02 UTC, Kafumio commented
你好，已按照你的要求进行修改

2023-06-22 10:17 UTC, pnck approved these changes

2023-06-24 07:36 UTC, merged

2023-06-24 07:36 UTC, piexlmax commented
可采纳进入测试和后期修改阶段。